import type { Exercise } from "./types";

export const EXERCISES: Exercise[] = [
  {
    id: "bench-press",
    name: "Nằm đẩy ngực",
    nameEn: "Bench Press",
    muscle: "chest",
    secondary: "triceps",
    equipment: "barbell",
    cues: "Hai chân chắc sàn, vai ép ghế. Hạ đòn chạm giữa ngực, đẩy thẳng lên. Không nẩy tạ trên ngực.",
  },
  {
    id: "incline-bench",
    name: "Đẩy ngực ghế nghiêng",
    nameEn: "Incline Bench Press",
    muscle: "chest",
    secondary: "shoulders",
    equipment: "barbell",
    cues: "Ghế 30–45°. Hạ đòn về xương đòn, đẩy theo đường hơi chéo. Ngực trên làm việc chính.",
  },
  {
    id: "db-bench",
    name: "Đẩy tạ đơn nằm",
    nameEn: "Dumbbell Bench Press",
    muscle: "chest",
    secondary: "triceps",
    equipment: "dumbbell",
    cues: "Tạ hạ sâu hơn đòn, lòng bàn tay hướng về phía trước. Ép ngực ở đỉnh, đừng chạm hai tạ vào nhau.",
  },
  {
    id: "incline-db",
    name: "Đẩy tạ đơn nghiêng",
    nameEn: "Incline Dumbbell Press",
    muscle: "chest",
    secondary: "shoulders",
    equipment: "dumbbell",
    cues: "Ghế nghiêng vừa. Hạ chậm, khuỷu ~45° so với thân. Đẩy lên hơi khép tạ.",
  },
  {
    id: "chest-fly",
    name: "Ép ngực tạ đơn",
    nameEn: "Dumbbell Fly",
    muscle: "chest",
    equipment: "dumbbell",
    cues: "Khuỷu hơi cong cố định. Hạ tạ rộng như ôm thùng, siết ngực khi khép. Đừng duỗi thẳng tay.",
  },
  {
    id: "cable-crossover",
    name: "Crossover cáp",
    nameEn: "Cable Crossover",
    muscle: "chest",
    equipment: "cable",
    cues: "Bước một chân trước, hơi cúi. Kéo hai tay vòng ra trước ngực, siết 1 giây rồi về chậm.",
  },
  {
    id: "push-up",
    name: "Chống đẩy",
    nameEn: "Push-up",
    muscle: "chest",
    secondary: "triceps",
    equipment: "bodyweight",
    cues: "Body một đường thẳng. Hạ ngực gần sàn, khuỷu 45°. Siết bụng, đừng võng lưng.",
  },
  {
    id: "chest-dip",
    name: "Dip ngực",
    nameEn: "Chest Dip",
    muscle: "chest",
    secondary: "triceps",
    equipment: "bodyweight",
    cues: "Hơi cúi người ra trước, khuỷu sát thân. Hạ đến khi vai thấp hơn khuỷu, đẩy lên siết ngực.",
  },
  {
    id: "deadlift",
    name: "Deadlift",
    nameEn: "Deadlift",
    muscle: "back",
    secondary: "hamstrings",
    equipment: "barbell",
    cues: "Đòn sát ống chân, lưng thẳng, hít bụng. Đẩy sàn bằng chân rồi siết hông. Không kéo bằng lưng.",
  },
  {
    id: "barbell-row",
    name: "Kéo tạ đòn",
    nameEn: "Barbell Row",
    muscle: "back",
    secondary: "biceps",
    equipment: "barbell",
    cues: "Cúi ~45°, lưng thẳng. Kéo đòn vào rốn dưới, siết vai sau. Hạ có kiểm soát.",
  },
  {
    id: "db-row",
    name: "Kéo tạ đơn",
    nameEn: "Dumbbell Row",
    muscle: "back",
    secondary: "biceps",
    equipment: "dumbbell",
    cues: "Một tay một gối trên ghế. Kéo tạ lên cạnh hông, khuỷu sát người. Đừng xoay thân.",
  },
  {
    id: "lat-pulldown",
    name: "Kéo xà xuống",
    nameEn: "Lat Pulldown",
    muscle: "back",
    secondary: "biceps",
    equipment: "cable",
    cues: "Hơi ngả sau. Kéo thanh xuống xương đòn, khuỷu xuống dưới. Siết lưng, đừng dùng đà.",
  },
  {
    id: "pull-up",
    name: "Hít xà",
    nameEn: "Pull-up",
    muscle: "back",
    secondary: "biceps",
    equipment: "bodyweight",
    cues: "Treo thẳng, siết vai xuống. Kéo cằm trên xà, hạ chậm. Không đung đưa.",
  },
  {
    id: "seated-row",
    name: "Kéo cáp ngồi",
    nameEn: "Seated Cable Row",
    muscle: "back",
    secondary: "biceps",
    equipment: "cable",
    cues: "Ngực mở, vai hạ. Kéo tay cầm vào bụng dưới, siết xương bả. Duỗi ra hết biên độ.",
  },
  {
    id: "face-pull",
    name: "Face pull",
    nameEn: "Face Pull",
    muscle: "shoulders",
    secondary: "back",
    equipment: "cable",
    cues: "Cáp ngang mặt. Kéo về mặt, khuỷu cao, xoay vai ngoài. Siết vai sau ở đỉnh.",
  },
  {
    id: "ohp",
    name: "Đẩy vai đứng",
    nameEn: "Overhead Press",
    muscle: "shoulders",
    secondary: "triceps",
    equipment: "barbell",
    cues: "Siết bụng mông. Đẩy đòn thẳng lên, đầu hơi lùi rồi xuyên qua. Khóa khuỷu ở đỉnh.",
  },
  {
    id: "db-shoulder-press",
    name: "Đẩy vai tạ đơn",
    nameEn: "Dumbbell Shoulder Press",
    muscle: "shoulders",
    secondary: "triceps",
    equipment: "dumbbell",
    cues: "Ngồi tựa nhẹ. Tạ ngang tai, đẩy lên không chạm nhau. Hạ chậm đến vai.",
  },
  {
    id: "arnold-press",
    name: "Arnold press",
    nameEn: "Arnold Press",
    muscle: "shoulders",
    equipment: "dumbbell",
    cues: "Bắt đầu lòng bàn tay hướng mặt, xoay ra ngoài khi đẩy lên. Nhịp chậm, kiểm soát vai.",
  },
  {
    id: "lateral-raise",
    name: "Dang tạ ngang",
    nameEn: "Lateral Raise",
    muscle: "shoulders",
    equipment: "dumbbell",
    cues: "Khuỷu mềm. Nâng tạ ngang vai, ngón út hơi cao. Không dùng đà từ thân.",
  },
  {
    id: "front-raise",
    name: "Nâng tạ trước",
    nameEn: "Front Raise",
    muscle: "shoulders",
    equipment: "dumbbell",
    cues: "Nâng trước mặt đến ngang vai, hạ chậm. Siết bụng để khỏi đung đưa.",
  },
  {
    id: "rear-delt-fly",
    name: "Ép vai sau",
    nameEn: "Rear Delt Fly",
    muscle: "shoulders",
    secondary: "back",
    equipment: "dumbbell",
    cues: "Cúi người, tay hơi cong. Dang tạ ra hai bên như mở cánh. Siết vai sau, không nhún lưng.",
  },
  {
    id: "squat",
    name: "Squat",
    nameEn: "Back Squat",
    muscle: "quads",
    secondary: "glutes",
    equipment: "barbell",
    cues: "Đòn trên trap, ngực mở. Ngồi hông ra sau, gối theo mũi chân. Đùi song song sàn rồi đứng lên.",
  },
  {
    id: "front-squat",
    name: "Squat trước",
    nameEn: "Front Squat",
    muscle: "quads",
    secondary: "core",
    equipment: "barbell",
    cues: "Đòn resting trên deltoid trước, khuỷu cao. Ngồi thẳng hơn back squat, giữ thân đứng.",
  },
  {
    id: "leg-press",
    name: "Đạp chân",
    nameEn: "Leg Press",
    muscle: "quads",
    secondary: "glutes",
    equipment: "machine",
    cues: "Chân rộng vừa, hạ sâu không nhấc mông. Đẩy gót, đừng khóa gối mạnh.",
  },
  {
    id: "lunge",
    name: "Lunge",
    nameEn: "Walking Lunge",
    muscle: "quads",
    secondary: "glutes",
    equipment: "dumbbell",
    cues: "Bước dài, gối trước trên mắt cá. Gối sau gần sàn. Thân thẳng, đẩy gót trước đứng lên.",
  },
  {
    id: "bulgarian-split",
    name: "Squat Bulgaria",
    nameEn: "Bulgarian Split Squat",
    muscle: "quads",
    secondary: "glutes",
    equipment: "dumbbell",
    cues: "Chân sau gác ghế. Hạ thẳng xuống, gối trước không vượt mũi chân quá nhiều. Kiểm soát thăng bằng.",
  },
  {
    id: "leg-extension",
    name: "Đá đùi trước",
    nameEn: "Leg Extension",
    muscle: "quads",
    equipment: "machine",
    cues: "Lưng tựa, đá đến khóa mềm, siết đùi 1 giây. Hạ chậm, đừng dùng đà.",
  },
  {
    id: "rdl",
    name: "RDL",
    nameEn: "Romanian Deadlift",
    muscle: "hamstrings",
    secondary: "glutes",
    equipment: "barbell",
    cues: "Gối mềm cố định. Đẩy hông ra sau, đòn sát chân. Kéo căng đùi sau rồi siết hông đứng lên.",
  },
  {
    id: "leg-curl",
    name: "Cuốn đùi sau",
    nameEn: "Lying Leg Curl",
    muscle: "hamstrings",
    equipment: "machine",
    cues: "Hông dính ghế. Cuốn gót về mông, siết 1 giây. Hạ chậm hết biên độ.",
  },
  {
    id: "hip-thrust",
    name: "Hip thrust",
    nameEn: "Hip Thrust",
    muscle: "glutes",
    secondary: "hamstrings",
    equipment: "barbell",
    cues: "Lưng trên tựa ghế, đòn trên hông. Đẩy hông đến thân-đùi một đường. Siết mông, đừng ưỡn lưng.",
  },
  {
    id: "calf-raise",
    name: "Nâng bắp chân",
    nameEn: "Standing Calf Raise",
    muscle: "calves",
    equipment: "machine",
    cues: "Hạ gót hết cỡ, nâng lên cao nhất, dừng 1 giây. Đầu gối thẳng mềm.",
  },
  {
    id: "barbell-curl",
    name: "Cuốn biceps",
    nameEn: "Barbell Curl",
    muscle: "biceps",
    equipment: "barbell",
    cues: "Khuỷu dính hông. Cuốn lên, siết đỉnh, hạ 2 giây. Đừng đung đưa thân.",
  },
  {
    id: "hammer-curl",
    name: "Hammer curl",
    nameEn: "Hammer Curl",
    muscle: "biceps",
    equipment: "dumbbell",
    cues: "Lòng bàn tay đối diện. Cuốn như cầm búa, khuỷu cố định. Làm chậm phần hạ.",
  },
  {
    id: "preacher-curl",
    name: "Preacher curl",
    nameEn: "Preacher Curl",
    muscle: "biceps",
    equipment: "dumbbell",
    cues: "Nách áp đệm. Duỗi gần thẳng rồi cuốn lên. Không nhấc vai khỏi ghế.",
  },
  {
    id: "tricep-pushdown",
    name: "Đẩy tay sau cáp",
    nameEn: "Tricep Pushdown",
    muscle: "triceps",
    equipment: "cable",
    cues: "Khuỷu dính sườn. Đẩy xuống khóa khuỷu, siết tay sau. Khuỷu không đi về trước.",
  },
  {
    id: "skull-crusher",
    name: "Skull crusher",
    nameEn: "Skull Crusher",
    muscle: "triceps",
    equipment: "barbell",
    cues: "Nằm, hạ đòn về trán/tóc, khuỷu hướng trần. Duỗi thẳng, đừng xòe khuỷu.",
  },
  {
    id: "oh-extension",
    name: "Duỗi tay sau trên đầu",
    nameEn: "Overhead Tricep Extension",
    muscle: "triceps",
    equipment: "dumbbell",
    cues: "Tạ sau đầu, khuỷu sát tai. Duỗi lên cao, hạ sâu căng tay sau. Siết bụng.",
  },
  {
    id: "close-grip-bench",
    name: "Nằm đẩy hẹp",
    nameEn: "Close-Grip Bench",
    muscle: "triceps",
    secondary: "chest",
    equipment: "barbell",
    cues: "Tay rộng bằng vai. Khuỷu sát thân khi hạ. Đẩy lên siết tay sau.",
  },
  {
    id: "plank",
    name: "Plank",
    nameEn: "Plank",
    muscle: "core",
    equipment: "bodyweight",
    cues: "Khuỷu dưới vai, body một đường. Siết bụng mông. Ghi số giây vào ô reps.",
  },
  {
    id: "hanging-raise",
    name: "Nâng chân treo",
    nameEn: "Hanging Leg Raise",
    muscle: "core",
    equipment: "bodyweight",
    cues: "Treo thẳng, nâng chân (hoặc gối) lên bằng cách cuộn xương chậu. Hạ chậm, đừng đung đưa.",
  },
  {
    id: "cable-crunch",
    name: "Crunch cáp",
    nameEn: "Cable Crunch",
    muscle: "core",
    equipment: "cable",
    cues: "Quỳ, kéo cáp bằng cách cuộn bụng, không gập hông. Siết 1 giây rồi về.",
  },
  {
    id: "russian-twist",
    name: "Russian twist",
    nameEn: "Russian Twist",
    muscle: "core",
    equipment: "dumbbell",
    cues: "Ngồi ngả sau, chân nâng. Xoay tạ sang hai bên, vai xoay theo. Ghi số lần mỗi bên.",
  },
];

const byId = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise | undefined {
  return byId.get(id);
}

export function requireExercise(id: string): Exercise {
  const e = byId.get(id);
  if (!e) {
    return {
      id,
      name: "Bài tập",
      nameEn: id,
      muscle: "chest",
      equipment: "barbell",
      cues: "",
    };
  }
  return e;
}
